services:
    db:
        image: postgres:alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        
        environment:
            - POSTGRES_DB=clinic_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-backend
        ports:
            - '${PORT}:3000'
        depends_on:
            - db